"""empty message

Revision ID: 5ef6f3c2b65f
Revises: ca6bd9c4413c
Create Date: 2019-12-11 00:53:41.934226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef6f3c2b65f'
down_revision = 'ca6bd9c4413c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'created_at')
    # ### end Alembic commands ###
