"""empty message

Revision ID: ca6bd9c4413c
Revises: 17707df4a7c2
Create Date: 2019-12-11 00:49:09.806782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca6bd9c4413c'
down_revision = '17707df4a7c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('body', sa.Text(), nullable=True))
    op.add_column('logs', sa.Column('headers', sa.JSON(), nullable=True))
    op.drop_column('logs', 'log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('log', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('logs', 'headers')
    op.drop_column('logs', 'body')
    # ### end Alembic commands ###
