"""empty message

Revision ID: ced3f91d3838
Revises: 5ef6f3c2b65f
Create Date: 2019-12-20 13:18:55.098115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ced3f91d3838'
down_revision = '5ef6f3c2b65f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('ip', postgresql.INET(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'ip')
    # ### end Alembic commands ###
